// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination ./mock_people.go --package gomock -source interface.go
//

// Package gomock is a generated GoMock package.
package gomock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPeople is a mock of People interface.
type MockPeople struct {
	ctrl     *gomock.Controller
	recorder *MockPeopleMockRecorder
	isgomock struct{}
}

// MockPeopleMockRecorder is the mock recorder for MockPeople.
type MockPeopleMockRecorder struct {
	mock *MockPeople
}

// NewMockPeople creates a new mock instance.
func NewMockPeople(ctrl *gomock.Controller) *MockPeople {
	mock := &MockPeople{ctrl: ctrl}
	mock.recorder = &MockPeopleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPeople) EXPECT() *MockPeopleMockRecorder {
	return m.recorder
}

// DescribeAge mocks base method.
func (m *MockPeople) DescribeAge() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAge")
	ret0, _ := ret[0].(string)
	return ret0
}

// DescribeAge indicates an expected call of DescribeAge.
func (mr *MockPeopleMockRecorder) DescribeAge() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAge", reflect.TypeOf((*MockPeople)(nil).DescribeAge))
}

// DescribeName mocks base method.
func (m *MockPeople) DescribeName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeName")
	ret0, _ := ret[0].(string)
	return ret0
}

// DescribeName indicates an expected call of DescribeName.
func (mr *MockPeopleMockRecorder) DescribeName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeName", reflect.TypeOf((*MockPeople)(nil).DescribeName))
}

// SaySame mocks base method.
func (m *MockPeople) SaySame(arg0 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaySame", arg0)
	ret0, _ := ret[0].(string)
	return ret0
}

// SaySame indicates an expected call of SaySame.
func (mr *MockPeopleMockRecorder) SaySame(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaySame", reflect.TypeOf((*MockPeople)(nil).SaySame), arg0)
}
